sudo: false
language: ruby
rvm:
  - ruby-head
install:
  - git clone https://github.com/ruby/mspec.git ../mspec
script:
  - gem install rdiscount
  - cat /home/travis/.rvm/gems/ruby-head/extensions/x86_64-linux/2.4.0/rdiscount-2.1.8/mkmf.log
branches:
  only:
    - master
    - /^try/
